"use strict";
// RDCP protocol error codes and types (pure protocol; no runtime logic)
Object.defineProperty(exports, "__esModule", { value: true });
exports.RDCP_ERROR_CODES = void 0;
exports.RDCP_ERROR_CODES = {
    // Authentication errors (4xx)
    RDCP_AUTH_REQUIRED: 'RDCP_AUTH_REQUIRED',
    RDCP_INVALID_TOKEN: 'RDCP_INVALID_TOKEN',
    RDCP_TOKEN_EXPIRED: 'RDCP_TOKEN_EXPIRED',
    RDCP_FORBIDDEN: 'RDCP_FORBIDDEN',
    RDCP_INVALID_CLIENT: 'RDCP_INVALID_CLIENT',
    // Validation errors (4xx)
    RDCP_VALIDATION_ERROR: 'RDCP_VALIDATION_ERROR',
    RDCP_INVALID_ACTION: 'RDCP_INVALID_ACTION',
    RDCP_INVALID_CATEGORY: 'RDCP_INVALID_CATEGORY',
    RDCP_CATEGORY_NOT_FOUND: 'RDCP_CATEGORY_NOT_FOUND',
    RDCP_MISSING_PARAMETER: 'RDCP_MISSING_PARAMETER',
    RDCP_INVALID_PROTOCOL: 'RDCP_INVALID_PROTOCOL',
    RDCP_NOT_FOUND: 'RDCP_NOT_FOUND',
    RDCP_RATE_LIMITED: 'RDCP_RATE_LIMITED',
    RDCP_REQUEST_ID_INVALID: 'RDCP_REQUEST_ID_INVALID',
    // Server errors (5xx)
    RDCP_SERVER_ERROR: 'RDCP_SERVER_ERROR',
    RDCP_INTERNAL_ERROR: 'RDCP_INTERNAL_ERROR',
    RDCP_UNAVAILABLE: 'RDCP_UNAVAILABLE',
    RDCP_TIMEOUT: 'RDCP_TIMEOUT',
    RDCP_CONFIGURATION_ERROR: 'RDCP_CONFIGURATION_ERROR',
    RDCP_STORAGE_ERROR: 'RDCP_STORAGE_ERROR',
    RDCP_AUDIT_WRITE_FAILED: 'RDCP_AUDIT_WRITE_FAILED',
    RDCP_RATE_LIMIT_MISCONFIGURED: 'RDCP_RATE_LIMIT_MISCONFIGURED',
    // Protocol errors
    RDCP_UNSUPPORTED_VERSION: 'RDCP_UNSUPPORTED_VERSION',
    RDCP_MALFORMED_REQUEST: 'RDCP_MALFORMED_REQUEST',
};
//# sourceMappingURL=errors.js.map